-- MySQL Script generated by MySQL Workbench
-- Mon Oct 17 10:03:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zhek
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zhek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zhek` DEFAULT CHARACTER SET utf8 ;
USE `zhek` ;

-- -----------------------------------------------------
-- Table `zhek`.`function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhek`.`function` (
  `idотрасль` INT NOT NULL,
  `название` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idотрасль`),
  UNIQUE INDEX `idотрасль_UNIQUE` (`idотрасль` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhek`.`brigades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhek`.`brigades` (
  `idбригады` INT NOT NULL,
  `отрасль` INT NOT NULL,
  PRIMARY KEY (`idбригады`, `отрасль`),
  INDEX `fk_бригады_отрасль_idx` (`отрасль` ASC) VISIBLE,
  UNIQUE INDEX `idбригады_UNIQUE` (`idбригады` ASC) VISIBLE,
  CONSTRAINT `fk_бригады_отрасль`
    FOREIGN KEY (`отрасль`)
    REFERENCES `zhek`.`function` (`idотрасль`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhek`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhek`.`Workers` (
  `idСотрудники` INT NOT NULL,
  `отдел` INT NOT NULL,
  `Имя` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `idСотрудники_UNIQUE` (`idСотрудники` ASC) VISIBLE,
  PRIMARY KEY (`idСотрудники`, `отдел`),
  INDEX `fk_Сотрудники_бригады_idx` (`отдел` ASC) VISIBLE,
  CONSTRAINT `fk_Сотрудники_бригады`
    FOREIGN KEY (`отдел`)
    REFERENCES `zhek`.`brigades` (`idбригады`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhek`.`Flats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhek`.`Flats` (
  `idКвартиры` INT NOT NULL,
  `комнаты` INT NOT NULL,
  `площадь` INT NOT NULL,
  `интернет_компания` VARCHAR(15) NULL,
  `посл_поверка` DATE NOT NULL,
  PRIMARY KEY (`idКвартиры`),
  UNIQUE INDEX `idКвартиры_UNIQUE` (`idКвартиры` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhek`.`Habitants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhek`.`Habitants` (
  `idЖильцы` INT NOT NULL,
  `квартира` INT NOT NULL,
  `имя` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idЖильцы`, `квартира`),
  INDEX `fk_жильцы_квартиры_idx` (`квартира` ASC) VISIBLE,
  UNIQUE INDEX `idЖильцы_UNIQUE` (`idЖильцы` ASC) VISIBLE,
  CONSTRAINT `fk_жильцы_квартиры`
    FOREIGN KEY (`квартира`)
    REFERENCES `zhek`.`Flats` (`idКвартиры`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhek`.`Statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhek`.`Statuses` (
  `idСтатусы` INT NOT NULL,
  `имя` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idСтатусы`),
  UNIQUE INDEX `idСтатусы_UNIQUE` (`idСтатусы` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhek`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhek`.`Tasks` (
  `idЗадача` INT NOT NULL,
  `Тип` ENUM("плановая", "внеплановая") NOT NULL,
  `Описание_задачи` VARCHAR(100) NOT NULL,
  `Заказчик` INT NOT NULL DEFAULT 1,
  `Время_появления` DATETIME NOT NULL,
  `Исполнитель` INT NOT NULL DEFAULT 1,
  `Время_завершения` DATETIME NULL,
  `Статус` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idЗадача`, `Статус`),
  INDEX `fk_Задачи_Статусы_idx` (`Статус` ASC) VISIBLE,
  INDEX `fk_Задачи_Жильцы_idx` (`Заказчик` ASC) VISIBLE,
  INDEX ` _idx` (`Исполнитель` ASC) VISIBLE,
  UNIQUE INDEX `idЗадача_UNIQUE` (`idЗадача` ASC) VISIBLE,
  CONSTRAINT `fk_Задачи_Статусы`
    FOREIGN KEY (`Статус`)
    REFERENCES `zhek`.`Statuses` (`idСтатусы`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Задачи_Жильцы`
    FOREIGN KEY (`Заказчик`)
    REFERENCES `zhek`.`Habitants` (`idЖильцы`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Задачи_Сотрудники`
    FOREIGN KEY (`Исполнитель`)
    REFERENCES `zhek`.`Workers` (`idСотрудники`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhek`.`story_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhek`.`story_work` (
  `idЗадача` INT NOT NULL,
  `Тип` ENUM("плановая", "внеплановая") NOT NULL,
  `Описание_задачи` VARCHAR(100) NOT NULL,
  `Заказчик` INT NOT NULL DEFAULT 1,
  `Время_появления` DATETIME NOT NULL,
  `Исполнитель` INT NOT NULL DEFAULT 1,
  `Время_завершения` DATETIME NULL,
  `Статус` INT NOT NULL DEFAULT 0,
  `инициатор_изменения` VARCHAR(45) NULL,
  `Время_изменения` DATETIME NULL,
  PRIMARY KEY (`idЗадача`, `Статус`),
  INDEX `fk_Задачи_Статусы_idx` (`Статус` ASC) VISIBLE,
  INDEX `fk_Задачи_Жильцы_idx` (`Заказчик` ASC) VISIBLE,
  INDEX ` _idx` (`Исполнитель` ASC) VISIBLE,
  UNIQUE INDEX `idЗадача_UNIQUE` (`idЗадача` ASC) VISIBLE,
  CONSTRAINT `fk_Задачи_Статусы1`
    FOREIGN KEY (`Статус`)
    REFERENCES `zhek`.`Statuses` (`idСтатусы`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Задачи_Жильцы1`
    FOREIGN KEY (`Заказчик`)
    REFERENCES `zhek`.`Habitants` (`idЖильцы`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Задачи_Сотрудники1`
    FOREIGN KEY (`Исполнитель`)
    REFERENCES `zhek`.`Workers` (`idСотрудники`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
